language: csharp

services:
  - docker
    
branches:
  only:
    - master

before_install:
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh

script:
  - docker build -t todolist .
    
deploy:
  - provider: script
    script:
      bash docker_push
      heroku container:release web --app $HEROKU_APP_NAME
    on:
      branch: master