services:
  - docker
    
branches:
  only:
    - master

script:
  - docker build -t todolist .
    
deploy:
  - provider: script
    script:
      ./docker_push.sh
    on:
      branch: master
      
after_deploy:
  - ./heroku_release.sh