services:
  - docker
    
branches:
  only:
    - master

script:
  - docker build -t todolist .
    
deploy:
  - provider: script
    script:
      bash docker_push
    on:
      branch: master
      
after_deploy:
  - bash heroku_release