services:
  - docker
    
branches:
  only:
    - master

before_install:
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh

script:
  - docker build -t todolist .
    
deploy:
  - provider: script
    script:
      docker login --username=_ --password=$HEROKU_TOKEN registry.heroku.com;
      docker tag todolist registry.heroku.com/$HEROKU_APP_NAME/web;
      docker push registry.heroku.com/$HEROKU_APP_NAME/web;
      heroku container:release web --app $HEROKU_APP_NAME
    on:
      branch: master